export const galleryPhotos = [
  {
    id: 'photo-1',
    url: '/images/engagement/PoradaProposal-29.webp',
    thumbnail: '/images/engagement/PoradaProposal-29.webp',
    caption: 'First look on the lawn',
    category: 'Getting Ready',
    location: 'The Lodge Lawn',
    date: '2025-05-10T14:00:00.000Z',
    likes: 24,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['first look', 'lawn', 'portrait'],
    faces: [
      { id: 'face-1', name: 'Austin', x: 38, y: 42 },
      { id: 'face-2', name: 'Jordyn', x: 62, y: 40 },
    ],
    created_at: '2025-05-10T14:00:00.000Z',
  },
  {
    id: 'photo-2',
    url: '/images/engagement/PoradaProposal-11.webp',
    thumbnail: '/images/engagement/PoradaProposal-11.webp',
    caption: 'Walking toward the ceremony garden',
    category: 'Ceremony',
    location: 'Ceremony Garden',
    date: '2025-05-10T15:30:00.000Z',
    likes: 58,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['ceremony', 'aisle', 'garden'],
    faces: [{ id: 'face-3', name: 'Jordyn', x: 51, y: 43 }],
    created_at: '2025-05-10T15:30:00.000Z',
  },
  {
    id: 'photo-3',
    url: '/images/engagement/PoradaProposal-150.webp',
    thumbnail: '/images/engagement/PoradaProposal-150.webp',
    caption: 'Quiet vows before the applause',
    category: 'Ceremony',
    location: 'Ceremony Garden',
    date: '2025-05-10T15:45:00.000Z',
    likes: 42,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['vows', 'ceremony', 'emotional'],
    faces: [
      { id: 'face-4', name: 'Austin', x: 35, y: 41 },
      { id: 'face-5', name: 'Jordyn', x: 65, y: 40 },
    ],
    created_at: '2025-05-10T15:45:00.000Z',
  },
  {
    id: 'photo-4',
    url: '/images/engagement/PoradaProposal-181.webp',
    thumbnail: '/images/engagement/PoradaProposal-181.webp',
    caption: 'The first kiss',
    category: 'Portraits',
    location: 'Ceremony Garden',
    date: '2025-05-10T16:00:00.000Z',
    likes: 89,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['portrait', 'first kiss', 'garden'],
    faces: [
      { id: 'face-6', name: 'Austin', x: 44, y: 45 },
      { id: 'face-7', name: 'Jordyn', x: 56, y: 45 },
    ],
    created_at: '2025-05-10T16:00:00.000Z',
  },
  {
    id: 'photo-5',
    url: '/images/engagement/PoradaProposal-255.webp',
    thumbnail: '/images/engagement/PoradaProposal-255.webp',
    caption: 'A table full of laughter',
    category: 'Reception',
    location: 'Reception Hall',
    date: '2025-05-10T18:30:00.000Z',
    likes: 36,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['family', 'reception', 'candids'],
    faces: [
      { id: 'face-8', name: 'Christine', x: 32, y: 51 },
      { id: 'face-9', name: 'Jerame', x: 69, y: 49 },
    ],
    created_at: '2025-05-10T18:30:00.000Z',
  },
  {
    id: 'photo-6',
    url: '/images/engagement/PoradaProposal-277.webp',
    thumbnail: '/images/engagement/PoradaProposal-277.webp',
    caption: 'First dance under the lights',
    category: 'Dancing',
    location: 'Reception Hall',
    date: '2025-05-10T19:00:00.000Z',
    likes: 67,
    photographer: 'Emma Photography',
    is_professional: true,
    tags: ['first dance', 'lights', 'dance floor'],
    faces: [
      { id: 'face-10', name: 'Austin', x: 40, y: 45 },
      { id: 'face-11', name: 'Jordyn', x: 61, y: 45 },
    ],
    created_at: '2025-05-10T19:00:00.000Z',
  },
] as const

export const guestbookMessagesWithComments = [
  {
    id: 'message-1',
    name: 'Sarah Mitchell',
    email: 'sarah@example.com',
    content:
      'Your vows made the whole room disappear for a second. It felt like all of us were holding our breath with you.',
    type: 'text',
    media_url: null,
    reactions: { heart: 12, clap: 4 },
    created_at: '2025-05-12T18:00:00.000Z',
    comments: [
      {
        id: 'comment-1',
        author: 'Austin',
        content: 'This is exactly how it felt. Thank you for being there.',
        created_at: '2025-05-12T20:30:00.000Z',
      },
    ],
  },
  {
    id: 'message-2',
    name: 'Mike Chen',
    email: 'mike@example.com',
    content: 'The dance floor was wild in the best way possible.',
    type: 'voice',
    media_url: null,
    reactions: { fire: 8 },
    created_at: '2025-05-13T18:00:00.000Z',
    comments: [],
  },
  {
    id: 'message-3',
    name: 'Aunt Patricia',
    email: 'patricia@example.com',
    content: 'We sent a quick video hello from our table right after the toasts.',
    type: 'video',
    media_url: null,
    reactions: { heart: 9 },
    created_at: '2025-05-14T18:00:00.000Z',
    comments: [],
  },
] as const

export const guestbookSubmitResponse = {
  success: true,
  message_id: 'message-new',
  error_message: '',
}

export const guestUploadInsertResponse = [
  {
    id: 'upload-1',
    guest_name: 'Test Guest',
    guest_email: 'guest@example.com',
    message: 'A few favorites from our table.',
    photo_urls: ['https://mock-storage.example.com/photo-1.webp'],
    video_urls: [],
    status: 'pending',
    created_at: '2025-05-16T10:00:00.000Z',
  },
]
