export { default as Home } from './Home'
export { default as Film } from './Film'
export { default as Gallery } from './Gallery'
export { default as Upload } from './Upload'
export { default as Guestbook } from './Guestbook'
