import { spawn } from 'node:child_process'
import { createRequire } from 'node:module'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import lighthouse from 'lighthouse'
import { launch } from 'chrome-launcher'

const require = createRequire(import.meta.url)
const config = require('../.lighthouserc.cjs')

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const tempRoot = path.join(rootDir, 'tmp', 'lhci')
const reportDate = new Date().toISOString().slice(0, 10)
const reportPath = path.join(rootDir, 'docs', 'archival', `PERFORMANCE_BASELINE_${reportDate}.md`)
const urls = config.ci.collect.url
const assertions = config.ci.assert.assertions

mkdirSync(tempRoot, { recursive: true })

const server = spawn(
  process.execPath,
  [
    path.join(rootDir, 'node_modules', 'vite', 'bin', 'vite.js'),
    'preview',
    '--host',
    '127.0.0.1',
    '--port',
    '4173',
    '--strictPort',
  ],
  {
    cwd: rootDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: process.env,
  }
)

server.stdout.on('data', chunk => process.stdout.write(chunk))
server.stderr.on('data', chunk => process.stderr.write(chunk))

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

async function waitForServer(url) {
  const deadline = Date.now() + 30_000
  while (Date.now() < deadline) {
    try {
      const response = await fetch(url)
      if (response.ok) return
    } catch {
      // Server is still starting.
    }
    await sleep(500)
  }
  throw new Error(`Timed out waiting for preview server at ${url}`)
}

function scorePercent(score) {
  return score === null ? 'n/a' : `${Math.round(score * 100)}`
}

function getThreshold(categoryId) {
  const assertion = assertions[`categories:${categoryId}`]
  if (!assertion) return null
  const [level, options] = assertion
  return { level, minScore: options.minScore }
}

function collectOpportunities(audits) {
  return Object.values(audits)
    .filter(audit => audit.score !== null && audit.score < 1)
    .map(audit => ({
      title: audit.title,
      score: audit.score,
      displayValue: audit.displayValue,
      savings:
        audit.details?.overallSavingsMs ??
        audit.numericValue ??
        (typeof audit.score === 'number' ? (1 - audit.score) * 1000 : 0),
    }))
    .sort((a, b) => b.savings - a.savings)
    .slice(0, 5)
}

function sanitizeText(value) {
  return String(value).replace(/\u00a0/g, ' ')
}

function routePath(url) {
  const parsed = new URL(url)
  return parsed.pathname === '/' ? '/' : parsed.pathname
}

async function writeReport(results, warnings, errors) {
  const lines = [
    `# Performance Baseline - ${reportDate}`,
    '',
    'Generated by `npm run perf` against the local production preview.',
    '',
    '## Scores',
    '',
    '| Route | Performance | Accessibility | Best Practices | SEO |',
    '| --- | ---: | ---: | ---: | ---: |',
  ]

  for (const result of results) {
    const categories = result.lhr.categories
    lines.push(
      `| ${routePath(result.url)} | ${scorePercent(categories.performance.score)} | ${scorePercent(categories.accessibility.score)} | ${scorePercent(categories['best-practices'].score)} | ${scorePercent(categories.seo.score)} |`
    )
  }

  lines.push('', '## Top Opportunities', '')

  for (const result of results) {
    lines.push(`### ${routePath(result.url)}`)
    const opportunities = collectOpportunities(result.lhr.audits)
    if (opportunities.length === 0) {
      lines.push('', '- No major opportunities reported.', '')
      continue
    }
    lines.push('')
    for (const opportunity of opportunities) {
      const detail = opportunity.displayValue ? ` (${sanitizeText(opportunity.displayValue)})` : ''
      lines.push(`- ${sanitizeText(opportunity.title)}${detail}`)
    }
    lines.push('')
  }

  lines.push('## Thresholds', '')
  lines.push('- Performance is warning-only at 60 while optimization work continues.')
  lines.push('- Accessibility remains an error threshold at 90.')
  lines.push('- Best Practices and SEO remain warning-only baselines.')

  if (warnings.length > 0) {
    lines.push('', '## Warnings', '')
    for (const warning of warnings) lines.push(`- ${warning}`)
  }

  if (errors.length > 0) {
    lines.push('', '## Errors', '')
    for (const error of errors) lines.push(`- ${error}`)
  }

  const prettier = await import('prettier')
  const formatted = await prettier.format(`${lines.join('\n')}\n`, { parser: 'markdown' })
  writeFileSync(reportPath, formatted)
}

let chrome

try {
  await waitForServer(urls[0])

  const userDataDir = path.join(tempRoot, `chrome-profile-${Date.now()}`)
  mkdirSync(userDataDir, { recursive: true })

  chrome = await launch({
    userDataDir,
    chromeFlags: ['--headless=new', '--disable-gpu', '--no-sandbox'],
    logLevel: 'error',
  })

  const results = []
  const warnings = []
  const errors = []

  for (const url of urls) {
    console.log(`Running Lighthouse on ${url}`)
    const result = await lighthouse(url, {
      port: chrome.port,
      output: 'json',
      logLevel: 'error',
    })

    if (!result) throw new Error(`Lighthouse did not return a result for ${url}`)
    results.push({ url, lhr: result.lhr })

    for (const category of Object.values(result.lhr.categories)) {
      const threshold = getThreshold(category.id)
      if (!threshold || category.score === null || category.score >= threshold.minScore) continue

      const message = `${routePath(url)} ${category.title} scored ${scorePercent(category.score)}; threshold is ${Math.round(threshold.minScore * 100)}`
      if (threshold.level === 'error') errors.push(message)
      else warnings.push(message)
    }
  }

  await writeReport(results, warnings, errors)
  console.log(`Performance baseline written to ${path.relative(rootDir, reportPath)}`)

  for (const warning of warnings) console.warn(`Warning: ${warning}`)
  if (errors.length > 0) {
    for (const error of errors) console.error(`Error: ${error}`)
    process.exitCode = 1
  }
} finally {
  if (chrome) chrome.kill()
  server.kill()

  try {
    rmSync(tempRoot, { recursive: true, force: true, maxRetries: 2 })
  } catch {
    // Chrome can briefly keep profile files locked on Windows; tmp/ is ignored.
  }
}
